DEVICE_PATH := device/Hisense/NOVA72671

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a9


# 没有 2nd_arch，电视是纯 32bit
TARGET_2ND_ARCH :=
TARGET_2ND_ARCH_VARIANT :=
TARGET_2ND_CPU_ABI :=
TARGET_2ND_CPU_ABI2 :=
TARGET_2ND_CPU_VARIANT :=

# Assert
TARGET_OTA_ASSERT_DEVICE := NOVA72671

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := NOVA72671
TARGET_NO_BOOTLOADER := true
TARGET_USES_UEFI := false

# Build
ALLOW_MISSING_DEPENDENCIES := true

# Platform
TARGET_BOARD_PLATFORM := n00010

# Kernel 通用旧平台配置（电视 8.0 基本都是这种）
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_CMDLINE := console=ttyS0,115200 root=/dev/mmcblk0p7 rootfstype=ext4 maxcpus=4 rootwait quiet no_console_suspend androidboot.hardware=n00010 earlycon=uart,mmio32,0xfd091000 firmware_class.path=/vendor/lib/firmware vmalloc=448M
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_TAGS_OFFSET := 0x00000100

# Prebuilt kernel
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb

# Partitions（电视老平台，无动态分区、无super、无VAB）
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432

BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := false

# 无动态分区、无AVB、无VNDK新版
BOARD_SUPER_PARTITION_SIZE := 0
BOARD_VNDK_VERSION := 26.1.0

# Recovery
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_NO_AB_UPDATES := true
TARGET_NO_DYNAMIC_PARTITIONS := true


# TWRP
TW_DEFAULT_LANGUAGE := zh_CN
TW_EXTRA_LANGUAGES := true
TW_THEME := landscape_hdpi
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_NO_SCREEN_TIMEOUT := true

# Debug
TARGET_USES_LOGD := true
TWRP_INCLUDE_LOGCAT := true

